version: "3.9"

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "80:80"
      - "81:81"   # panel de administraci√≥n
      - "443:443"
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - validocu_net
    restart: unless-stopped

networks:
  validocu_net:
