version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: validocu_pg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: validocu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data  # ‚Üê quitamos el init.sql
    networks:
      - validocu_network

volumes:
  pgdata:

networks:
  validocu_network:
    external: true