services:
  ia-api:
    container_name: ia-api
    build:
      context: .
      dockerfile: Dockerfile.fast
      target: runtime
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - ./app:/app/app:rw
      - ./outputs:/app/outputs:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
