version: '3.9'

services:
  ia-api:
    container_name: ia-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - ./app:/app/app
      - ./outputs:/app/outputs
      - ./outputs/modelo_multiclase:/app/modelo_multiclase
    command: uvicorn app.main:app --host 0.0.0.0 --port 5050 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - validocu_network

networks:
  validocu_network:
    external: true